const app = document.querySelector('#app');
const toastElement = document.querySelector('#toast');
const KEY = 'capiturk-web-v1';
const fresh = () => ({name:'',learningName:'',goal:'Для путешествий',minutes:10,city:'Antalya',favorite:'Kahve',onboarded:false,sound:true,completed:[],favorites:[],sessions:{},activity:{},finalCompleted:false});
let state; try { state={...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}; } catch { state=fresh(); }
let data, lessons, route={page:state.onboarded?'home':'welcome'}, onboarding=0, selected=null, chosenTokens=[], tokenOrder=[], checked=false, passed=false, translated=false, transcript=false, search='',filter='all';
let recorder=null,stream=null,recordURL=null,recordTimeout,recordStarted=0,recordRequest=0,speechSerial=0,toastTimer,audioContext;
const paths={
 arrow:'M4 12h16m-6-6 6 6-6 6',back:'m14 5-7 7 7 7',close:'m6 6 12 12M18 6 6 18',
 home:'m3 10 9-7 9 7v10H3V10m6 10v-7h6v7',book:'M4 4h6a3 3 0 0 1 2 3v14a4 4 0 0 0-4-2H3V4h1m16 0h-6a3 3 0 0 0-2 3m0 14a4 4 0 0 1 4-2h5V4h-1',
 map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5m6-2v16m6-14v16',chart:'M4 20V12h3v8H4m7 0V4h3v16h-3m7 0V8h3v12h-3',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',
 heart:'M12 21 3.5 12.5C-2 5.5 7 0 12 7c5-7 14-1.5 8.5 5.5L12 21',cup:'M4 8h12v7a6 6 0 0 1-12 0V8m12 1h2a3 3 0 0 1 0 6h-2M3 22h16M7 2v3m5-3v3',
 mug:'M5 7h11v13H5V7m11 2h3a3 3 0 0 1 0 6h-3M8 2v2m5-2v2',drop:'M12 2C9 7 5 10 5 15a7 7 0 0 0 14 0c0-5-4-8-7-13Z',
 sun:'M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2',
 wave:'M5 12V7a1.5 1.5 0 0 1 3 0v4-7a1.5 1.5 0 0 1 3 0v7-8a1.5 1.5 0 0 1 3 0v8-6a1.5 1.5 0 0 1 3 0v8l2-2c2-2 4 0 2 2l-4 6c-4 5-11 3-12-2l-2-4c-1-2 1-3 2-1Z',
 smile:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20M7 9h.01M17 9h.01M7 14q5 7 10 0',
 check:'m5 12 4 4L19 6',clock:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20m0 4v6l4 3',
 chat:'M3 3h18v13H9l-6 5V3m5 5h8m-8 4h5',plane:'m2 11 8 1 7-9 3 1-4 9 5 4-1 2-7-3-5 5-2-1 2-6-6-1v-2',
 case:'M3 7h18v14H3V7m5 0V3h8v4M3 12h18m-10-2v5h2v-5',person:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 22v-3a8 8 0 0 1 16 0v3',
 sound:'m3 9 5 0 5-5v16l-5-5H3V9m14-2q6 5 0 10m-1-7q3 2 0 4',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0V5m-3 6v1a6 6 0 0 0 12 0v-1m-6 7v4m-4 0h8',
 play:'m8 4 12 8-12 8V4',stop:'M5 5h14v14H5Z',star:'m12 2 3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1 3-6',
 lock:'M6 10h12v11H6V10m2 0V6a4 4 0 0 1 8 0v4m-4 5v2',flame:'M13 2c1 6-4 7-3 11-3-1-3-3-3-3-8 11 12 16 12 4 0-5-4-6-6-12Z',
 left:'M20 12H4m6-6-6 6 6 6',right:'M4 12h16m-6-6 6 6-6 6',pin:'M12 22s8-9 8-14a8 8 0 1 0-16 0c0 5 8 14 8 14ZM12 5a3 3 0 1 0 0 6 3 3 0 0 0 0-6',
 car:'M3 10 6 3h12l3 7v9H3v-9m0 0h18M6 15h2m8 0h2M5 19v3m14-3v3',ticket:'M3 5h18v5a2 2 0 0 0 0 4v5H3v-5a2 2 0 0 0 0-4V5m12 0v3m0 3v2m0 3v3',
 bed:'M3 3v19m18-13v13M3 17h18M3 9h18v8M6 9V6h6v3',building:'M5 22V2h14v20M2 22h20M8 6h1m6 0h1M8 10h1m6 0h1M8 14h1m6 0h1M10 22v-5h4v5',
 pharmacy:'M3 7h18v15H3V7m5 0V3h8v4m-4 4v7m-3.5-3.5h7',basket:'M3 9h18l-2 12H5L3 9m3 0 4-7m8 7-4-7M9 13v4m6-4v4',
 food:'M4 2v7q3 3 6 0V2M7 2v20M18 2c-5 5-4 10 0 10V2m0 10v10',receipt:'M5 2h14v20l-3-2-4 2-4-2-3 2V2m4 5h6m-6 4h6m-6 4h3',
 crown:'m2 5 5 5 5-8 5 8 5-5-3 15H5L2 5',sparkles:'m12 3 2 6 6 3-6 2-2 6-2-6-6-2 6-3 2-6M21 2v4m-2-2h4',trash:'M3 6h18M8 6V3h8v3M5 6l1 16h12l1-16M10 10v8m4-8v8'
};
const symbolMap={'hand.wave':'wave','sun.max':'sun','bubble.left':'chat','face.smiling':'smile','heart':'heart','checkmark.circle':'check','xmark.circle':'close','hands.sparkles':'sparkles','cup.and.saucer':'cup','mug':'mug','drop':'drop','drop.fill':'drop','fork.knife':'food','doc.text':'receipt','car':'car','bed.double':'bed','airplane':'plane','ticket':'ticket','location':'pin','mappin':'pin','mappin.and.ellipse':'pin','basket':'basket','cross.case':'pharmacy','arrow.right':'right','arrow.left':'left','figure.walk':'person','person':'person','person.text.rectangle':'person','house':'home','briefcase':'case','building.2':'building','book':'book','suitcase.rolling':'case','map':'map','bubble.left.and.bubble.right':'chat'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[symbolMap[name]||name]||paths.sparkles}"/></svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const attr=esc;
const brand=()=>'<span class="brand">Capi<span>türk</span></span>';
const button=(label,action,extra='',cls='primary',disabled=false)=>`<button class="${cls}" data-act="${action}" ${extra} ${disabled?'disabled':''}>${label}</button>`;
const nextButton=(label,action,extra='',disabled=false)=>button(`${label}${icon('arrow')}`,action,extra,'primary',disabled);
const hero=(cls='',caption='')=>`<div class="hero ${cls}"><img src="capi.png" alt="Капибара Капи с розовым бантом и чашкой кофе"><span class="heart" aria-hidden="true">♡</span>${caption?`<span class="hero-caption">${caption}</span>`:''}</div>`;
const topbar=(back=null)=>`<header class="topbar">${back?button(icon('back'),back,'aria-label="Назад"','circle'):brand()}${back?brand():''}${back?'<span style="width:48px"></span>':`<span class="round-label">${icon('flame')}${streak()} ${streak()===1?'день':'дн.'}</span>`}</header>`;
const tabs=()=>`<nav class="tabbar" aria-label="Разделы приложения">${[['home','home','Главная'],['course','map','Курс'],['words','book','Слова'],['progress','chart','Прогресс'],['settings','settings','Настройки']].map(([id,i,l])=>button(`${icon(i)}<span>${l}</span>`,'nav',`data-page="${id}" ${route.page===id?'aria-current="page"':''}`,route.page===id?'active':'')).join('')}</nav>`;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('Браузер не смог сохранить прогресс. Проверь свободное место и настройки Safari.');}}
function toast(message){clearTimeout(toastTimer);toastElement.textContent=message;toastElement.classList.add('visible');toastTimer=setTimeout(()=>toastElement.classList.remove('visible'),5000);}
function dateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function streak(){let day=new Date(),count=0;if(!state.activity[dateKey(day)])day.setDate(day.getDate()-1);while(state.activity[dateKey(day)]){count++;day.setDate(day.getDate()-1);}return count;}
function resolve(template){const cities={Antalya:["Antalya'da",'в Анталье'],İstanbul:["İstanbul'da",'в Стамбуле'],Ankara:["Ankara'da",'в Анкаре'],İzmir:["İzmir'de",'в Измире']};const city=cities[state.city]||cities.Antalya;const map={name:state.learningName.trim()||state.name.trim()||'Deniz',city:state.city,cityLocative:city[0],cityRussian:city[1],favorite:state.favorite,favoriteRussian:{Kahve:'кофе',Çay:'чай',Türkiye:'Турцию'}[state.favorite]};return String(template??'').replace(/\{([^}]+)\}/g,(_,key)=>map[key]??'');}
const normalize=s=>s.replaceAll('’',"'").toLocaleLowerCase('tr').replace(/[\p{P}\s]+/gu,' ').trim();
const displayTokens=t=>t.join(' ').replace(/\s+([,.!?])/g,'$1');
const currentLesson=()=>lessons.find(l=>l.id===route.lesson);
const freshSession=()=>({position:0,visited:[],correct:[],spoken:[],listened:[],readInstead:[],attempts:{}});
function sessionKey(l){return route.preview&&route.lesson===l.id?'preview-'+l.id:l.id;}
function getSession(l=currentLesson()){const key=sessionKey(l);return state.sessions[key]??(state.sessions[key]=freshSession());}
const currentExercise=()=>currentLesson().exercises[getSession().position];
const graded=e=>['choice','listen','build','gap','dialogue','map'].includes(e.kind);
const audioRequired=e=>['listen','scene'].includes(e.kind);
const add=(list,v)=>{if(!list.includes(v))list.push(v);};
const unlocked=l=>Array.from({length:l.id},(_,i)=>i).every(i=>state.completed.includes(i));
const mastered=l=>l.id===5?state.finalCompleted:state.completed.includes(l.id);
const nextLesson=()=>data.lessons.find(l=>!state.completed.includes(l.id))||data.finalConversation;
function cleanAudio(){speechSerial++;window.speechSynthesis?.cancel();recordRequest++;if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());stream=null;clearTimeout(recordTimeout);if(recordURL){URL.revokeObjectURL(recordURL);recordURL=null;}}
function navigate(page,lesson){cleanAudio();route={page,...(lesson!==undefined?{lesson}:{})};render();window.scrollTo({top:0,behavior:'instant'});}
function prepareStep(){cleanAudio();const e=currentExercise();selected=getSession().correct.includes(e.id)?e.answer:null;chosenTokens=[];tokenOrder=(e.tokens||[]).map((_,i)=>i).sort(()=>Math.random()-.5);passed=getSession().correct.includes(e.id);checked=passed;translated=false;transcript=false;}
function canContinue(){const e=currentExercise(),s=getSession();return (!graded(e)||passed)&&(!audioRequired(e)||s.listened.includes(e.id)||s.readInstead.includes(e.id))&&(e.kind!=='speak'||s.spoken.includes(e.id))&&recorder?.state!=='recording';}
function page(content,cls='',nav=true){app.innerHTML=`<main class="page ${cls} ${nav?'':'no-nav'}">${content}</main>${nav?tabs():''}`;}
function profileFields(){return `<div class="card flat"><label class="field"><span>Имя в турецких фразах · лучше латиницей</span><input data-field="learningName" value="${attr(state.learningName)}" placeholder="${attr(state.name||'Deniz')}" autocomplete="given-name" maxlength="40"></label><label class="field"><span>Город для рассказа</span><select data-field="city">${['Antalya','İstanbul','Ankara','İzmir'].map(c=>`<option ${state.city===c?'selected':''}>${c}</option>`).join('')}</select></label><label class="field"><span>Мне нравится</span><select data-field="favorite">${[['Kahve','Кофе'],['Çay','Чай'],['Türkiye','Турция']].map(([v,l])=>`<option value="${v}" ${state.favorite===v?'selected':''}>${l}</option>`).join('')}</select></label><p class="tiny muted">Можно использовать вымышленный профиль для практики.</p></div>`;}
function welcome(){app.innerHTML=`<main class="welcome">${brand()}<p class="tagline">Маленькие шаги<br>к большим историям</p>${hero()}<div class="welcome-box"><h1>Merhaba!</h1><p class="muted">Будем учить<br>турецкий вместе?</p>${nextButton('Давай начнём','onboard')}<div class="dots" aria-hidden="true"><i class="on"></i><i></i><i></i><i></i></div></div></main>`;}
function onboard(){let content='';if(onboarding===0){content=`<h1 class="onboard-title">Как тебя зовут?</h1><p class="lead">Капи будет рядом на твоём пути к турецкому.</p><label class="field"><span>Твоё имя</span><input data-field="name" value="${attr(state.name)}" placeholder="Например, Дарина" autocomplete="given-name" maxlength="40"></label>${hero('short')}`;}else if(onboarding===1){content=`<h1 class="onboard-title">Для чего тебе<br>турецкий сейчас?</h1><p class="lead">Выбери, что тебе ближе.</p><div class="stack gap-sm">${[['Для путешествий','plane'],['Для жизни в Турции','building'],['Для общения','heart'],['Для себя','sparkles']].map(([v,i])=>button(`${icon(i)}<span class="choice-label">${v}</span><span class="radio"></span>`,'goal',`data-value="${v}"`,'choice '+(state.goal===v?'chosen':''))).join('')}</div>`;}else{content=`<h1 class="onboard-title">В твоём темпе</h1><p class="lead">Лучше понемногу, но регулярно.</p><div class="stack gap-sm">${[5,10,15,20].map(v=>button(`${icon('clock')}<span class="choice-label">${v} минут<br><span class="small muted">${v===10?'Комфортный ежедневный темп':'Твой маленький шаг'}</span></span><span class="radio"></span>`,'minutes',`data-value="${v}"`,'choice '+(state.minutes===v?'chosen':''))).join('')}</div><p class="small muted" style="margin:22px 0">5 уроков, 32 активных слова — и твой первый разговор.</p>`;}page(`${topbar('onboard-back')}<div class="progress-track"><div class="progress-fill" style="width:${(onboarding+1)/3*100}%"></div></div>${content}<div class="lesson-footer">${nextButton(onboarding===2?'Начать обучение':'Продолжить','onboard-next')}</div>`,'',false);}
function home(){const l=nextLesson();page(`${topbar()}<h1>${state.name?`Привет,<br>${esc(state.name)}!`:'Merhaba, друг!'}</h1><p class="lead">Сегодня отличный день<br>для турецкого <span style="color:var(--coral)">♡</span></p>${hero('','Küçük adımlar, büyük hikâyeler.')}<button class="card plan row" data-act="intro" data-id="${l.id}"><div class="grow"><h3>Твой план на сегодня</h3><p class="small muted">Одна история · цель ${state.minutes} минут</p></div><span class="circle peach">${icon('arrow')}</span></button><div class="section-title"><h3>${state.finalCompleted?'Повторим разговор':'Продолжить'}</h3><span>Модуль 01</span></div><button class="card lesson-tile row" data-act="intro" data-id="${l.id}"><div class="tile-icon">${icon(l.symbol)}</div><div class="grow"><h3>${esc(l.title)}</h3><p class="small muted">${l.id===5?'Твоя первая беседа':`История ${l.id+1} из 5`}</p></div><span style="color:var(--coral)">${icon('play')}</span></button><p class="note">Каждое слово — маленький шаг вперёд ♡</p>`,'home');}
function course(){page(`${topbar()}<div class="eyebrow">Модуль 01 · начало истории</div><h1>Твой путь</h1><p class="lead">От первого merhaba<br>до маленького разговора.</p><div class="course-line">${lessons.map(l=>`<button class="course-item ${!unlocked(l)?'locked':''} ${l.id===5?'final':''}" data-act="intro" data-id="${l.id}"><div class="tile-icon">${icon(l.symbol,'lg')}</div><div class="grow"><div class="step-label">${l.id===5?'ФИНАЛ МОДУЛЯ':`ИСТОРИЯ 0${l.id+1}`}</div><h3>${esc(l.title)}</h3><p class="tiny muted" style="margin-top:6px">${esc(l.goal)}</p></div>${icon(mastered(l)?'check':unlocked(l)?'arrow':'lock','end')}</button>`).join('')}</div><p class="note">Sen yaparsın! — У тебя получится ♡</p>`);}
function intro(){const l=currentLesson();page(`${topbar('back-course')}<div class="eyebrow">${l.id===5?'Финал первого модуля':`История 0${l.id+1}`}</div><h1>${esc(l.title)}</h1><p class="lead">${esc(l.goal)}</p>${hero('short')}<div class="card intro-meta" style="margin:20px 0"><div class="row">${icon('book')}<span class="grow">Новые слова</span><span class="small">${l.id===5?'Только знакомые':l.newWords.length}</span></div><div class="row">${icon('sparkles')}<span class="grow">Практика</span><span class="small">${l.exercises.filter(graded).length} заданий</span></div><div class="row">${icon('chat')}<span class="grow">${l.id===5?'Итоговый разговор':'Мини-диалог'}</span><span class="small">1</span></div></div>${l.reviewWords.length?`<p class="small muted" style="margin:18px 0">Вспомним: ${l.reviewWords.map(esc).join(' · ')}</p>`:''}${l.id>=4?profileFields():''}<div class="lesson-footer">${unlocked(l)?nextButton(mastered(l)?'Пройти ещё раз':getSession(l).position?'Продолжить урок':'Начать урок','start'):nextButton('Сначала предыдущий урок','previous')}${!unlocked(l)?button('Посмотреть этот урок','preview-start','','secondary'):''}</div>`,'',false);}
function audioButton(text){return button(icon('sound'),'speak',`data-text="${attr(resolve(text))}" aria-label="Послушать турецкое произношение"`,'audio-btn');}
function choices(e){return `<div class="stack gap-sm">${(e.options||[]).map(o=>button(`${o.symbol?icon(o.symbol):'<span class="radio"></span>'}<span class="choice-label">${esc(resolve(o.text))}</span>${passed&&selected===o.id?icon('check'):''}`,'choice',`data-id="${o.id}"`,'choice '+(selected===o.id?'chosen ':'')+(passed&&selected===o.id?'correct':''),passed||(e.kind==='listen'&&!getSession().listened.includes(e.id)&&!getSession().readInstead.includes(e.id)))).join('')}</div>`;}
function map(e){const building=(name,i)=>`<div class="map-building">${icon(i,'lg')}<b>${name}</b></div>`;return `<div class="card mini-map" role="img" aria-label="Карта: аптека ${e.direction==='right'?'справа':'слева'} от тебя"><div class="map-buildings">${building(e.direction==='left'?'Eczane':'Market',e.direction==='left'?'pharmacy':'basket')}<div class="map-street"></div>${building(e.direction==='right'?'Eczane':'Market',e.direction==='right'?'pharmacy':'basket')}</div><div class="map-road">${icon('left')}<span></span>${icon('person')}<span></span>${icon('right')}</div><p class="map-you">Ты здесь · смотришь вперёд</p></div>`;}
function lesson(){const l=currentLesson(),s=getSession(),e=currentExercise();let content='';const phraseCard=(text,translation)=>`<div class="card phrase-card"><p class="phrase">${esc(resolve(text))}</p>${translation?`<p class="muted">${esc(resolve(translation))}</p>`:''}<div class="audio-row">${audioButton(text)}</div></div>`;
 switch(e.kind){
 case 'scene':content=hero('short')+phraseCard(e.text,e.translation);break;
 case 'word':{const w=[...l.newWords,...l.extraWords].find(w=>w.turkish===e.word);content=`<div class="card word-card"><div class="object">${icon(w.symbol,'xl')}</div><h2>${esc(w.turkish)}</h2>${w.pronunciation?`<p class="small muted" style="margin-top:5px">${esc(w.pronunciation)}</p>`:''}<p class="meaning">${esc(w.russian)}</p>${audioButton(w.turkish)}<div class="example"><p style="font-size:19px">${esc(resolve(w.example))}</p><p class="small muted" style="margin:8px 0">${esc(resolve(w.exampleTranslation))}</p>${button('Послушать пример','speak',`data-text="${attr(resolve(w.example))}"`,'text-button')}</div></div>`;break;}
 case 'phrase':content=phraseCard(e.text,e.translation);break;
 case 'choice':content=(e.symbol?`<div class="card word-card" style="min-height:160px"><div class="object" aria-label="Вода">${icon(e.symbol,'xl')}</div></div>`:'')+choices(e);break;
 case 'gap':content=`<div class="card phrase-card"><p class="phrase">${esc(resolve(e.text))}</p></div>`+choices(e);break;
 case 'listen':content=hero('short')+`<div class="audio-row">${audioButton(e.text)}</div><p class="small muted center">${s.listened.includes(e.id)?'Послушай ещё раз или выбери ответ':'Нажми на звук и послушай до конца'}</p>`+choices(e);break;
 case 'build':content=`<div class="card build-answer">${passed?esc(resolve(e.text)):chosenTokens.length?esc(displayTokens(chosenTokens.map(i=>resolve(e.tokens[i])))):'<span class="muted small">Твоя фраза появится здесь…</span>'}</div>${!passed&&chosenTokens.length?button('Убрать последнее слово','undo','','text-button'):''}<div class="token-grid">${tokenOrder.map(i=>button(esc(resolve(e.tokens[i])),'token',`data-index="${i}"`,'token '+(chosenTokens.includes(i)?'used':''),passed||chosenTokens.includes(i))).join('')}</div>`;break;
 case 'speak':content=phraseCard(e.text,e.translation)+button(`${icon(recorder?.state==='recording'?'stop':'mic')} ${recorder?.state==='recording'?'Остановить запись':'Записать свой голос'}`,'record','','secondary '+(recorder?.state==='recording'?'recording':''))+(recordURL?`<audio controls src="${recordURL}"></audio>`:'')+button(s.spoken.includes(e.id)?'Повторение отмечено ✓':'Я попробовала произнести без записи','spoken','','text-button')+`<p class="small muted center">${s.spoken.includes(e.id)?'Спасибо за попытку ♡ Можно повторить чуть медленнее.':'Повтори сама или запиши голос. Автоматической оценки произношения здесь нет.'}</p>`;break;
 case 'dialogue':content=(e.text?`<div class="card phrase-card"><div class="eyebrow">Капи говорит</div><p class="phrase">${esc(resolve(e.text))}</p>${!e.hideTranslation&&e.translation?(translated?`<p class="small muted">${esc(resolve(e.translation))}</p>`:button('Показать перевод','translate','','text-button')):''}<div class="audio-row">${audioButton(e.text)}</div></div>`:'')+choices(e);break;
 case 'map':content=map(e)+choices(e);break;
 case 'profile':content=profileFields()+hero('short');break;
 }
 const audioFallback=audioRequired(e)&&!s.listened.includes(e.id)?`<div class="center">${button(transcript?'Фраза показана':'Не слышно? Показать текст','transcript','','text-button')}${transcript?`<div class="speech-transcript">${esc(resolve(e.text))}</div><p class="tiny muted">Текстовый режим: аудирование не засчитывается.</p>`:''}</div>`:'';
 const ready=e.kind==='build'?chosenTokens.length===(e.tokens||[]).length:selected!==null;
 const feedback=checked?`<div class="feedback ${passed?'':'wrong'}" role="status">${passed?'Harika! Всё верно ♡':'Давай попробуем ещё раз, не спеша.'}</div>`:'';
 page(`<header class="topbar lesson-header">${button(icon('close'),'pause','aria-label="Сохранить и выйти"','circle')}<div class="progress-track" role="progressbar" aria-valuenow="${s.position+1}" aria-valuemin="0" aria-valuemax="${l.exercises.length}"><div class="progress-fill" style="width:${s.position/l.exercises.length*100}%"></div></div><span class="counter">${s.position+1}/${l.exercises.length}</span></header>${route.preview?'<p class="eyebrow">Просмотр · без зачёта прогресса</p>':''}<div class="lesson-content">${e.isFinal?'<div class="eyebrow">Применяем в жизни</div>':''}<h1>${esc(e.title)}</h1><p class="muted">${esc(resolve(e.prompt))}</p>${content}${audioFallback}</div><div class="lesson-footer">${feedback}${graded(e)&&!passed?button('Проверить','check','','primary',!ready):nextButton(s.position===l.exercises.length-1?'Завершить':'Продолжить','next','',!canContinue())}</div>`,'',false);
}
function complete(){const l=currentLesson();page(`<div class="completion"><div class="stars" aria-hidden="true">✧ · ✦ · ✧</div><h1>${route.preview?'Спасибо за практику!':l.id===5?'Sen Türkçe<br>konuşuyorsun! ♡':'Урок пройден!'}</h1><p class="lead">${esc(l.result)}</p>${hero()}<div class="card stats">${[[l.id===5?32:l.newWords.length,'слов'],[l.id===5?15:l.phrases.length,'основных фраз'],[l.id===5?5:1,'мини-диалог']].map(([v,k])=>`<div><b>${v}</b><span>${k}</span></div>`).join('')}</div><p class="small muted" style="margin:20px 0">${route.needsAudio?'Осталось аудирование. Вернись к заданиям со звуком, чтобы завершить урок.':route.preview?'Это был просмотр урока. Для зачёта пройди модуль по порядку.':l.id===5?'Твоя первая история на турецком состоялась.':'Ещё один маленький шаг к большим историям.'}</p>${route.needsAudio?nextButton('Вернуться к аудированию','start'):nextButton('Продолжить','back-course')}</div>`,'',false);}
function wordList(){let words=data.lessons.filter(l=>filter!=='learned'||state.completed.includes(l.id)).flatMap(l=>[...l.newWords,...l.extraWords]);words=words.filter(w=>(filter!=='saved'||state.favorites.includes(w.turkish))&&(!search||`${w.turkish} ${w.russian}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())));return words.length?words.map(w=>`<div class="word-row"><span class="symbol">${icon(w.symbol)}</span><div class="grow"><h3>${esc(w.turkish)}</h3><p class="translation">${esc(w.russian)}</p></div>${button(icon('sound'),'speak',`data-text="${attr(w.turkish)}" aria-label="Послушать ${attr(w.turkish)}"`,'circle')}${button(icon('heart'),'favorite',`data-word="${attr(w.turkish)}" aria-label="${state.favorites.includes(w.turkish)?'Убрать из избранного':'Добавить в избранное'} ${attr(w.turkish)}" aria-pressed="${state.favorites.includes(w.turkish)}"`,'circle '+(state.favorites.includes(w.turkish)?'saved':''))}</div>`).join(''):'<div class="empty">Пока здесь тихо.<br><span class="small">Добавь любимое слово или измени поиск.</span></div>';}
function dictionary(){page(`${topbar()}<h1>Твои маленькие<br>открытия</h1><p class="lead">Слова, из которых складываются истории.</p><input id="word-search" type="search" placeholder="Слово или перевод" aria-label="Поиск по словарю" value="${attr(search)}"><div class="segmented">${[['all','Все'],['learned','Изучены'],['saved','Избранное']].map(([v,l])=>button(l,'filter',`data-value="${v}"`,filter===v?'selected':'')).join('')}</div><div id="word-list">${wordList()}</div>`);}
function progress(){const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i-6);return d;});const count=data.lessons.filter(l=>state.completed.includes(l.id)).reduce((a,l)=>a+l.newWords.length,0);page(`${topbar()}<h1>Твой прогресс</h1><p class="lead">Каждое слово — уже шаг вперёд.</p><div class="card row">${icon('flame','lg')}<div><h2>${streak()} ${streak()===1?'день':'дн.'} подряд</h2><p class="small muted">${streak()?'Так держать ♡':'Начни свою маленькую историю'}</p></div></div><div class="week">${days.map(d=>`<div class="day ${state.activity[dateKey(d)]?'done':''}"><span>${d.toLocaleDateString('ru',{weekday:'short'})}</span><b>${state.activity[dateKey(d)]?'✓':d.getDate()}</b></div>`).join('')}</div><div class="card"><div class="row" style="justify-content:space-between"><h3>Первый модуль</h3><span class="small muted">${state.completed.length+(state.finalCompleted?1:0)} / 6</span></div><div class="progress-track" style="margin:17px 0"><div class="progress-fill" style="width:${(state.completed.length+(state.finalCompleted?1:0))/6*100}%"></div></div><p class="small muted">Изучено активных слов: ${count} из 32</p></div><div class="section-title"><h3>Мои достижения</h3></div><div class="badges">${[['star','Первые слова',count>=7],['flame','Три дня подряд',streak()>=3],['crown','Первый разговор',state.finalCompleted]].map(([i,t,yes])=>`<div class="badge ${yes?'earned':''}"><div>${icon(yes?i:'lock')}</div><span>${t}</span></div>`).join('')}</div>${hero('short')}`);}
function settings(){page(`${topbar()}<h1>В твоём темпе</h1><p class="lead">Маленькие привычки,<br>большие истории.</p>${hero('short')}<div class="stack" style="margin-top:20px"><div class="card"><h3>Твой профиль</h3><label class="field"><span>Имя</span><input data-field="name" value="${attr(state.name)}" maxlength="40" placeholder="Твоё имя"></label><p class="small muted">${esc(state.goal)}</p></div>${profileFields()}<div class="card"><h3>Ежедневная цель</h3><div class="segmented">${[5,10,15,20].map(v=>button(`${v} мин`,'setting-minutes',`data-value="${v}"`,state.minutes===v?'selected':'')).join('')}</div><div class="setting-line"><span>Звуки ответов</span>${button('','sound',`role="switch" aria-checked="${state.sound}" aria-label="Звуки ответов"`,'switch '+(state.sound?'on':''))}</div></div><div class="card install-card"><strong>Capitürk на экране «Домой»</strong><p>В Safari нажми «Поделиться» → «На экран “Домой”». Капи будет в одном касании.</p></div><p class="privacy">Это браузерная версия для знакомства с приложением. Прогресс сохраняется только в этом браузере. Записи голоса никуда не отправляются. Для озвучки нужен турецкий голос устройства.</p>${button('Сбросить данные этого браузера','reset','','text-button danger')}</div>`);}
function render(){if(!data)return;const routes={welcome,onboard,home,course,intro,lesson,complete,words:dictionary,progress,settings};(routes[route.page]||home)();}
function beep(success=true){if(!state.sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.type='sine';o.frequency.setValueAtTime(success?660:230,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(success?880:180,audioContext.currentTime+.14);g.gain.setValueAtTime(.045,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.24);o.start();o.stop(audioContext.currentTime+.25);}catch{}}
function speak(text,element){if(!('speechSynthesis'in window)){toast('Озвучка недоступна в этом браузере. Открой приложение в Safari.');return;}const synth=window.speechSynthesis,voice=synth.getVoices().find(v=>v.lang.toLowerCase().startsWith('tr'));if(!voice){toast('Турецкий голос пока недоступен. Попробуй Safari на iPhone или открой текст под заданием.');return;}speechSerial++;const serial=speechSerial,exerciseID=route.page==='lesson'?currentExercise().id:null;const lessonID=route.lesson;synth.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='tr-TR';u.voice=voice;u.rate=.78;element?.classList.add('playing');u.onend=()=>{element?.classList.remove('playing');if(serial===speechSerial&&route.page==='lesson'&&route.lesson===lessonID&&currentExercise().id===exerciseID&&text===resolve(currentExercise().text)){add(getSession().listened,exerciseID);save();render();}};u.onerror=()=>{element?.classList.remove('playing');toast('Звук не удалось воспроизвести. Попробуй ещё раз.');};synth.speak(u);}
async function record(){if(recorder?.state==='recording'){recorder.stop();stream?.getTracks().forEach(t=>t.stop());clearTimeout(recordTimeout);return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('Запись недоступна. Можно повторить вслух без записи.');return;}const request=++recordRequest,id=currentExercise().id,lessonID=route.lesson;try{const acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(request!==recordRequest||route.page!=='lesson'||currentExercise().id!==id){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;window.speechSynthesis?.cancel();const chunks=[];const rec=new MediaRecorder(stream);recorder=rec;recordStarted=Date.now();rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=()=>{acquired.getTracks().forEach(t=>t.stop());if(route.page==='lesson'&&route.lesson===lessonID&&currentExercise().id===id&&request===recordRequest){if(Date.now()-recordStarted>=500){if(recordURL)URL.revokeObjectURL(recordURL);recordURL=URL.createObjectURL(new Blob(chunks,{type:rec.mimeType}));add(getSession().spoken,id);save();}render();}};rec.start();recordTimeout=setTimeout(()=>{if(rec.state==='recording')rec.stop();},45000);render();}catch{toast('Микрофон не включён. Можно повторить без записи и отметить попытку.');}}
function satisfied(l,s){return l.exercises.every(e=>s.visited.includes(e.id)&&(!graded(e)||s.correct.includes(e.id))&&(e.kind!=='speak'||s.spoken.includes(e.id))&&(!audioRequired(e)||s.listened.includes(e.id)));}
function start(preview=false){const l=currentLesson();if(!preview&&!unlocked(l))return;cleanAudio();route={page:'lesson',lesson:l.id,preview};if(mastered(l)||preview)state.sessions[sessionKey(l)]=freshSession();prepareStep();save();render();window.scrollTo(0,0);}
app.addEventListener('click',event=>{const el=event.target.closest('[data-act]');if(!el||el.disabled)return;const action=el.dataset.act;switch(action){
 case'nav':navigate(el.dataset.page);break;
 case'onboard':route={page:'onboard'};onboarding=0;render();break;
 case'onboard-back':if(onboarding>0){onboarding--;render();}else navigate('welcome');break;
 case'onboard-next':if(onboarding<2){onboarding++;render();window.scrollTo(0,0);}else{state.onboarded=true;save();navigate('home');}break;
 case'goal':state.goal=el.dataset.value;save();render();break;
 case'minutes':case'setting-minutes':state.minutes=Number(el.dataset.value);save();render();break;
 case'intro':navigate('intro',Number(el.dataset.id));break;
 case'back-course':navigate('course');break;
 case'previous':navigate('intro',nextLesson().id);break;
 case'start':start(false);break;
 case'preview-start':start(true);break;
 case'pause':save();navigate('intro',route.lesson);break;
 case'speak':speak(el.dataset.text,el);break;
 case'translate':translated=true;render();break;
 case'transcript':transcript=true;add(getSession().readInstead,currentExercise().id);save();render();break;
 case'choice':selected=el.dataset.id;checked=false;render();break;
 case'token':chosenTokens.push(Number(el.dataset.index));checked=false;render();break;
 case'undo':chosenTokens.pop();checked=false;render();break;
 case'check':{const e=currentExercise(),s=getSession();passed=e.kind==='build'?normalize(chosenTokens.map(i=>resolve(e.tokens[i])).join(' '))===normalize(resolve(e.text)):selected===e.answer;checked=true;s.attempts[e.id]=(s.attempts[e.id]||0)+1;if(passed)add(s.correct,e.id);save();beep(passed);render();break;}
 case'next':{if(!canContinue())return;const l=currentLesson(),s=getSession();add(s.visited,currentExercise().id);if(s.position<l.exercises.length-1){s.position++;prepareStep();save();render();window.scrollTo(0,0);}else{const real=!route.preview&&unlocked(l)&&satisfied(l,s);if(real){if(l.id===5)state.finalCompleted=true;else add(state.completed,l.id);state.activity[dateKey()]=(state.activity[dateKey()]||0)+1;}else if(!route.preview){s.position=Math.max(0,l.exercises.findIndex(e=>audioRequired(e)&&!s.listened.includes(e.id)));toast('Практика завершена. Для зачёта аудирования вернись к заданиям со звуком.');}const preview=!real,needsAudio=!real&&!route.preview;save();cleanAudio();route={page:'complete',lesson:l.id,preview,needsAudio};beep();render();window.scrollTo(0,0);}break;}
 case'record':record();break;
 case'spoken':add(getSession().spoken,currentExercise().id);save();render();break;
 case'filter':filter=el.dataset.value;render();break;
 case'favorite':{const w=el.dataset.word;state.favorites=state.favorites.includes(w)?state.favorites.filter(x=>x!==w):[...state.favorites,w];save();document.querySelector('#word-list').innerHTML=wordList();break;}
 case'sound':state.sound=!state.sound;save();render();break;
 case'reset':if(confirm('Удалить профиль, избранное и прогресс только в этом браузере?')){cleanAudio();state=fresh();save();navigate('welcome');}break;
 }});
app.addEventListener('input',e=>{if(e.target.id==='word-search'){search=e.target.value;document.querySelector('#word-list').innerHTML=wordList();}else if(e.target.dataset.field){state[e.target.dataset.field]=e.target.value;save();}});
app.addEventListener('change',e=>{if(e.target.dataset.field){state[e.target.dataset.field]=e.target.value;save();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){cleanAudio();save();}});
window.addEventListener('pagehide',()=>{cleanAudio();save();});
try{const response=await fetch('./module.json');if(!response.ok)throw Error('content');data=await response.json();lessons=[...data.lessons,data.finalConversation];window.speechSynthesis?.getVoices();render();}catch{app.innerHTML=`<main class="loading">${brand()}<p>Не удалось загрузить уроки.<br>Проверь интернет и обнови страницу.</p><button class="primary" onclick="location.reload()">Попробовать снова</button></main>`;}
