import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AudioButton, Button, Capi, colors as c, Icon, Progress, radius } from './design';
import { fill, Lesson, lessons, Mood, Profile, vocabulary } from './learning';

export function Home({ profile, start }: { profile: Profile; start: (l: Lesson) => void }) {
  const next = lessons.find(l => !profile.completed.includes(l.id));
  const count = profile.completed.length;
  const step = next ? profile.positions[next.id] || 0 : 0;
  return <><View style={t.greeting}><View style={{ flex: 1 }}><Text style={t.kicker}>MERHABA, {profile.name.toLocaleUpperCase('tr')} ♡</Text><Text style={t.title}>{count === 6 ? 'Ты столько уже умеешь' : count ? 'Продолжим твою историю?' : 'Турецкий начинается\nс маленького шага'}</Text></View></View><Text style={t.secondary}>{count ? 'Каждый разговор становится чуть ближе.' : 'Немного практики. Много маленьких открытий.'}</Text><View style={t.hero}><Capi mood={count === 6 ? 'celebration' : count ? 'correct' : 'cozy_home'} height={250} badge /><View style={t.plan}><View style={t.row}><Text style={t.kicker}>{next ? 'ТВОЙ ПЛАН НА СЕГОДНЯ' : 'ПЕРВЫЙ МОДУЛЬ ПРОЙДЕН'}</Text><Text style={t.time}>{profile.minutes} мин</Text></View><Text style={t.lessonTitle}>{next?.title || 'Вернуться к любимым словам'}</Text><Text style={t.secondary}>{next?.goal || 'Повторение поможет чувствовать себя увереннее.'}</Text>{next && <View style={[t.row, { marginVertical: 4 }]}><Progress value={step / next.exercises.length} /><Text style={t.small}>{step}/{next.exercises.length}</Text></View>}<Button title={next ? step ? 'Продолжить урок  →' : 'Начать урок  →' : 'Повторить первый урок  →'} onPress={() => start(next || lessons[0])} /></View></View><View style={t.milestone}><Icon name="sparkles-outline" /><Text style={t.small}>{count} из 6 уроков · {count ? 'Ты уже продвинулась вперёд' : 'Твой путь только начинается'}</Text></View></>;
}
export function Course({ profile, start }: { profile: Profile; start: (l: Lesson) => void }) {
  const next = lessons.find(l => !profile.completed.includes(l.id));
  const moods: Mood[] = ['welcome', 'cafe', 'travel', 'city', 'profile', 'celebration'];
  return <><Text style={t.kicker}>ТВОЙ МАРШРУТ · МОДУЛЬ 01</Text><Text style={t.title}>Первые разговоры</Text><Text style={t.secondary}>От «привет» до своей маленькой истории.</Text><View style={t.journey}>{lessons.map((l, i) => {
    const completed = profile.completed.includes(l.id), current = next?.id === l.id, unlocked = i === 0 || profile.completed.includes(lessons[i - 1].id);
    return <View key={l.id} style={t.stop}><View style={t.rail}>{i !== 5 && <View style={[t.line, completed && { backgroundColor: c.accentCoral }]} />}<View style={[t.number, (current || completed) && { backgroundColor: c.accentPeach }]}>{completed ? <Icon name="checkmark" size={18} /> : unlocked ? <Text style={t.numberText}>{i + 1}</Text> : <Icon name="lock-closed-outline" size={15} color={c.textSecondary} />}</View></View><View style={[t.stopBody, { marginLeft: i % 2 ? 12 : 0 }, current && t.current]}>{current && <View style={t.currentMascot}><Capi mood={moods[i]} height={116} /></View>}<Text style={t.kicker}>{completed ? 'ЗАВЕРШЕНО' : current ? 'ТВОЙ СЛЕДУЮЩИЙ ШАГ' : `УРОК ${i + 1}`}</Text><Pressable disabled={!unlocked} accessibilityRole="button" accessibilityState={{ disabled: !unlocked }} accessibilityLabel={l.title} onPress={() => start(l)}><Text style={[t.lessonTitle, !unlocked && { color: c.textSecondary }, current && { maxWidth: '100%' }]}>{l.title}</Text></Pressable>{current ? <><Text style={[t.secondary, { maxWidth: '100%' }]}>{l.goal}</Text><Button title="К уроку  →" onPress={() => start(l)} /></> : <Text style={t.small}>{completed ? 'Можно повторить в любой момент' : 'Откроется после предыдущего урока'}</Text>}</View></View>;
  })}</View></>;
}
export function Words({ profile, update, speak }: { profile: Profile; update: (p: Partial<Profile>) => void; speak: (text: string, rate?: number) => void }) {
  const [section, setSection] = useState('Слова'); const [filter, setFilter] = useState('Все'); const [query, setQuery] = useState('');
  const known = profile.knownWords || [];
  const learned = new Set(lessons.filter(l => profile.completed.includes(l.id)).flatMap(l => [...l.newWords || [], ...l.extraWords || []].map(w => w.turkish)));
  const words = vocabulary.filter(w => (filter === 'Все' || (filter === 'Знаю' ? known.includes(w.turkish) : learned.has(w.turkish) && !known.includes(w.turkish))) && `${w.turkish} ${w.russian}`.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')));
  return <><Text style={t.kicker}>ТВОЯ КОЛЛЕКЦИЯ</Text><Text style={t.title}>Слова для жизни</Text><Text style={t.secondary}>Послушай, вспомни, произнеси.</Text><View style={t.tabs}>{['Слова','Фразы','Диалоги'].map(x => <Tab key={x} text={x} active={section === x} onPress={() => setSection(x)} />)}</View>{section === 'Слова' ? <><View style={t.search}><Icon name="search-outline" size={18} /><TextInput style={t.searchInput} value={query} onChangeText={setQuery} placeholder="Турецкое слово или перевод" placeholderTextColor={c.textSecondary} accessibilityLabel="Найти слово" /></View><View style={t.tabs}>{['Все','Повторить','Знаю'].map(x => <Tab key={x} text={x} active={filter === x} onPress={() => setFilter(x)} />)}</View>{!words.length && <View style={t.empty}><Capi mood="sleepy" height={130} /><Text style={t.lessonTitle}>{query ? 'Пока ничего не нашлось' : filter === 'Знаю' ? 'Твоя коллекция будет расти' : 'Первые слова ещё впереди'}</Text><Text style={t.secondary}>{query ? 'Попробуй другое слово или перевод.' : 'Проходи уроки и отмечай знакомые слова сердечком.'}</Text><Button title="Показать все слова" soft onPress={() => { setQuery(''); setFilter('Все'); }} /></View>}{words.map(w => <View key={w.turkish} style={t.word}><View style={t.row}><View style={{ flex: 1 }}><AudioButton text={w.turkish} speak={speak} compact slow /><Text style={t.secondary}>{w.russian}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={known.includes(w.turkish) ? `Убрать ${w.turkish} из знакомых` : `Уже знаю ${w.turkish}`} accessibilityState={{ selected: known.includes(w.turkish) }} onPress={() => update({ knownWords: known.includes(w.turkish) ? known.filter(x => x !== w.turkish) : [...known, w.turkish] })} style={t.heart}><Icon name={known.includes(w.turkish) ? 'heart' : 'heart-outline'} size={20} /></Pressable></View><AudioButton compact text={fill(w.example, profile)} speak={speak} /><Text style={t.small}>{fill(w.exampleTranslation, profile)}</Text></View>)}</> : lessons.map(l => <View key={l.id}><Text style={t.section}>{l.title}</Text>{(section === 'Фразы' ? l.phrases || [] : l.miniDialogue || []).map((p, i) => <View key={i} style={t.word}><AudioButton compact text={fill(p.turkish, profile)} speak={speak} /><Text style={t.secondary}>{fill(p.russian, profile)}</Text></View>)}</View>)}</>;
}
function Tab({ text, active, onPress }: { text: string; active: boolean; onPress: () => void }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected: active }} onPress={onPress} style={[t.tab, active && { backgroundColor: c.successSoft }]}><Text style={{ fontSize: 14, fontWeight: active ? '600' : '400', color: active ? c.accentCoral : c.textSecondary }}>{text}</Text></Pressable>; }
const t = StyleSheet.create({
  kicker: { color: c.accentCoral, fontSize: 10, letterSpacing: 1.2, fontWeight: '600' }, title: { color: c.textPrimary, fontSize: 30, lineHeight: 35, fontWeight: '600', letterSpacing: -.8 }, secondary: { color: c.textSecondary, fontSize: 15, lineHeight: 21 }, small: { color: c.textSecondary, fontSize: 12, lineHeight: 18 }, greeting: { gap: 8 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, justifyContent: 'space-between' }, hero: { marginTop: -12 }, plan: { marginTop: -28, padding: 20, borderRadius: radius.large, gap: 12, backgroundColor: c.surfaceGlass, borderColor: c.dividerSoft, borderWidth: .5, shadowColor: '#A26A50', shadowOpacity: .05, shadowRadius: 20, shadowOffset: { width: 0, height: 4 } }, lessonTitle: { fontSize: 20, lineHeight: 26, fontWeight: '500', color: c.textPrimary }, time: { color: c.accentCoral, fontSize: 12 }, milestone: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginVertical: 4 }, journey: { marginTop: 24 }, stop: { flexDirection: 'row' }, rail: { width: 40, alignItems: 'center' }, line: { position: 'absolute', width: 1, top: 24, bottom: -12, backgroundColor: c.dividerSoft }, number: { width: 32, height: 32, borderRadius: 16, backgroundColor: c.surfaceSecondary, alignItems: 'center', justifyContent: 'center', marginTop: 4 }, numberText: { color: c.textPrimary, fontSize: 14 }, stopBody: { flex: 1, gap: 8, padding: 12, paddingBottom: 32 }, current: { backgroundColor: c.successSoft, borderRadius: radius.large, padding: 20, marginBottom: 24, gap: 16 }, currentMascot: { alignSelf: 'center', width: 116 }, tabs: { flexDirection: 'row', gap: 4 }, tab: { paddingHorizontal: 16, paddingVertical: 12, borderRadius: radius.capsule, minHeight: 44 }, search: { borderWidth: .5, borderColor: c.dividerSoft, borderRadius: radius.medium, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 16, backgroundColor: c.surfaceGlass }, searchInput: { fontSize: 14, color: c.textPrimary, flex: 1, minHeight: 48 }, word: { borderBottomWidth: .5, borderColor: c.dividerSoft, paddingVertical: 16, gap: 4 }, heart: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, section: { fontSize: 19, color: c.textPrimary, fontWeight: '600', marginTop: 20 }, empty: { gap: 16, padding: 16, alignItems: 'stretch' },
});
